apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: portal-api-linked
spec:
  type: openapi
  lifecycle: experimental
  owner: guests
  system: examples
  definition: 
    $text: https://github.com/filipesman/test/blob/main/vehicle.yaml
